- name: install nginx
  yum:
    name:
      - nginx
    state: latest

- name: permit traffic in default zone for https service
  ansible.posix.firewalld:
    service: http
    permanent: yes
    state: enabled

- name: Copy nginx.conf
  copy:
    src: /etc/ansible/roles/http/files/nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'

- name: change user for nginx
  lineinfile:
    path: /etc/nginx/nginx.conf
    regexp: '^user nginx;$'
    line: 'user {{ username }};'
  notify: manage nginx service

