---
 - hosts: test
   gather_facts: false
   tasks:
     - name: download noarch
       ansible.builtin.get_url:
         url: https://dev.mysql.com/get/mysql80-community-release-el7-5.noarch.rpm
         dest: /opt/
     - name: add repo
       ansible.builtin.yum:
         name: /root/mysql80-community-release-el7-5.noarch.rpm
         state: present
     - name: install mySQL server
       ansible.builtin.yum:
         name: mysql-server
         state: present
     - name: Make sure a service unit is running
       ansible.builtin.systemd:
         state: started
         name: mysqld