---
- name: add user and generate key
  user:
      name: "{{ username }}"
      generate_ssh_key: yes
- name: Set authorized key 
  ansible.posix.authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ lookup('file', '/home/{{ username }}/.ssh/id_rsa.pub') }}"
