---
- name: install dnsmasq
  yum:
    name: dnsmasq
    state: present
- name: Set configuration file
  copy:
    content: "files/dnsmasq.conf"
    dest: "/etc/dnsmasq.conf"
    mode: 0644
- name: service start
  service:
    name: dnsmasq
    state: started
    enabled: yes 